name: {{project_name.snakeCase()}}
description: {{description}}
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.2
  provider: ^6.1.2
  {{#use_api}}
  dio: ^5.7.0
  {{/use_api}}
  {{#use_go_router}}
  go_router: ^14.6.2
  {{/use_go_router}}
  {{#use_local_storage}}
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  {{/use_local_storage}}
  {{#include_example_feature}}
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  url_launcher: ^6.3.1
  json_annotation: ^4.9.0
  {{/include_example_feature}}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  {{#include_example_feature}}
  mockito: ^5.4.4
  mocktail: ^1.0.3
  build_runner: ^2.4.13
  {{/include_example_feature}}
  {{#use_local_storage}}
  hive_generator: ^2.0.1
  {{/use_local_storage}}

flutter:
  uses-material-design: true
