name: {{project_name.snakeCase()}}
description: {{description}}
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  {{#use_api}}dio: ^5.7.0{{/use_api}}
  get_it: ^8.0.2
  go_router: ^14.6.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.3
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
